// Firebase configuration for the Magic Bracket worker.
//
// Hand-maintained rather than regenerated by `flutterfire configure` so
// we can keep the cross-platform `signInWithProvider` setup in one
// place. Same Firebase project for every target; the OAuth client ID
// below is the iOS-type client that `signInWithProvider` consults on
// macOS and that the Windows/Linux desktop implementations reuse via
// the project's federated config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        // The desktop platforms all use the same Firebase project; the
        // Windows-specific `appId` mirrors the macOS one because they
        // share an OAuth client (federated via Firebase Console).
        return desktop;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions has no entry for $defaultTargetPlatform. '
          'Run `flutterfire configure` to add it, or set up the platform '
          'manually here.',
        );
    }
  }

  // OAuth client ID (iOS-type in GCP Console). `firebase_auth.signIn-
  // WithProvider` picks this up automatically on macOS; on Windows /
  // Linux the desktop implementation reuses the same Firebase project's
  // federated config and falls back to a system-browser OAuth flow.
  static const _iosClientId =
      '14286370379-echlkrv6jd11ep7341irajaf8anr3f1i.apps.googleusercontent.com';

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevBZ3RfwNtrqW7L2ICgmV8QkvoDDvNbc',
    appId: '1:14286370379:ios:eb91598352257eef6d7fce',
    messagingSenderId: '14286370379',
    projectId: 'magic-bracket-simulator',
    databaseURL: 'https://magic-bracket-simulator-default-rtdb.firebaseio.com',
    storageBucket: 'magic-bracket-simulator.firebasestorage.app',
    iosClientId: _iosClientId,
    iosBundleId: 'com.tytaniumdev.magicBracketSimulator',
  );

  /// Windows + Linux desktop config. Same Firebase project; appId
  /// differs from macOS only by the platform prefix Firebase expects.
  /// firebase_auth_desktop reuses the iOS-type OAuth client over the
  /// system browser, so we keep the `iosClientId` field populated.
  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyDevBZ3RfwNtrqW7L2ICgmV8QkvoDDvNbc',
    appId: '1:14286370379:web:eb91598352257eef6d7fce',
    messagingSenderId: '14286370379',
    projectId: 'magic-bracket-simulator',
    databaseURL: 'https://magic-bracket-simulator-default-rtdb.firebaseio.com',
    storageBucket: 'magic-bracket-simulator.firebasestorage.app',
    iosClientId: _iosClientId,
    iosBundleId: 'com.tytaniumdev.magicBracketSimulator',
  );
}
