// Firebase configuration for the Magic Bracket worker.
//
// Hand-maintained rather than regenerated by `flutterfire configure` so
// we can keep the cross-platform `signInWithProvider` setup in one
// place. Same Firebase project for every target; the OAuth client ID
// below is the iOS-type client that `signInWithProvider` consults on
// macOS and that the Windows/Linux desktop implementations reuse via
// the project's federated config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        // The desktop platforms all use the same Firebase project; the
        // Windows-specific `appId` mirrors the macOS one because they
        // share an OAuth client (federated via Firebase Console).
        return desktop;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions has no entry for $defaultTargetPlatform. '
          'Run `flutterfire configure` to add it, or set up the platform '
          'manually here.',
        );
    }
  }

  // OAuth client ID (iOS-type in GCP Console). `firebase_auth.signIn-
  // WithProvider` picks this up automatically on macOS.
  static const _iosClientId =
      '14286370379-echlkrv6jd11ep7341irajaf8anr3f1i.apps.googleusercontent.com';

  /// OAuth client ID for the macOS + Windows + Linux PKCE flow. A
  /// "Desktop application" type client in GCP Console — distinct
  /// from the iOS-type client above, which doesn't accept
  /// `http://127.0.0.1` loopback redirect URIs.
  static const desktopOAuthClientId =
      '14286370379-t5bj865bhp31k4170lh03cre44b7r1e2.apps.googleusercontent.com';

  /// Google requires a `client_secret` on Desktop OAuth token
  /// exchange even when PKCE is in use — RFC 7636 was meant to make
  /// this optional but Google enforces it for the Desktop client
  /// type. Per their own "Native App" docs, the value isn't a real
  /// secret; it just identifies the app to Google. Safe to embed in
  /// the binary.
  ///
  /// If this is empty the macOS/Windows AuthGate sees
  /// "client_secret is missing" from Google's token endpoint.
  /// Google requires `client_secret` on Desktop OAuth token exchange
  /// even with PKCE — RFC 7636 was meant to make this optional, but
  /// Google enforces it on Desktop client types. Per Google's own
  /// "Native App" docs the value isn't a real secret, but we keep
  /// it out of source anyway. Release builds + local dev inject it
  /// via `--dart-define` from Doppler (`blinkbreak/prd`, key
  /// `GOOGLE_DESKTOP_OAUTH_CLIENT_SECRET`).
  ///
  /// Local dev:
  ///   doppler run --project blinkbreak --config prd -- sh -c \
  ///     'flutter run -d macos \
  ///        --dart-define=GOOGLE_DESKTOP_OAUTH_CLIENT_SECRET="$GOOGLE_DESKTOP_OAUTH_CLIENT_SECRET"'
  ///
  /// Empty here → AuthService surfaces a clearly-named error before
  /// touching Google's token endpoint (which would otherwise return
  /// the cryptic 400 "client_secret is missing").
  static const desktopOAuthClientSecret = String.fromEnvironment(
    'GOOGLE_DESKTOP_OAUTH_CLIENT_SECRET',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDevBZ3RfwNtrqW7L2ICgmV8QkvoDDvNbc',
    appId: '1:14286370379:ios:eb91598352257eef6d7fce',
    messagingSenderId: '14286370379',
    projectId: 'magic-bracket-simulator',
    databaseURL: 'https://magic-bracket-simulator-default-rtdb.firebaseio.com',
    storageBucket: 'magic-bracket-simulator.firebasestorage.app',
    iosClientId: _iosClientId,
    iosBundleId: 'com.tytaniumdev.magicBracketSimulator',
  );

  /// Windows + Linux desktop config. Same Firebase project; appId
  /// differs from macOS only by the platform prefix Firebase expects.
  /// firebase_auth_desktop reuses the iOS-type OAuth client over the
  /// system browser, so we keep the `iosClientId` field populated.
  static const FirebaseOptions desktop = FirebaseOptions(
    apiKey: 'AIzaSyDevBZ3RfwNtrqW7L2ICgmV8QkvoDDvNbc',
    appId: '1:14286370379:web:eb91598352257eef6d7fce',
    messagingSenderId: '14286370379',
    projectId: 'magic-bracket-simulator',
    databaseURL: 'https://magic-bracket-simulator-default-rtdb.firebaseio.com',
    storageBucket: 'magic-bracket-simulator.firebasestorage.app',
    iosClientId: _iosClientId,
    iosBundleId: 'com.tytaniumdev.magicBracketSimulator',
  );
}
