#!/usr/bin/env bash
set -euo pipefail

# setup-worker.sh — Bootstrap a remote worker machine from GCP Secret Manager.
#
# Prerequisites:
#   - gcloud CLI installed and authenticated:
#       gcloud auth application-default login
#       gcloud config set project <PROJECT_ID>
#   - Docker installed and running
#   - jq installed (brew install jq / apt install jq)
#
# Usage:
#   ./scripts/setup-worker.sh                    # standard setup
#   ./scripts/setup-worker.sh --worker-id=mac1   # with a worker identifier

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
WORKER_DIR="$REPO_ROOT/worker"
SECRET_NAME="worker-host-config"

# ── Parse arguments ──────────────────────────────────────────────────
WORKER_ID=""
for arg in "$@"; do
  case $arg in
    --worker-id=*) WORKER_ID="${arg#*=}" ;;
    --help|-h)
      echo "Usage: $0 [--worker-id=NAME]"
      echo ""
      echo "Bootstraps a remote worker by reading config from GCP Secret Manager."
      echo "Prerequisites: gcloud CLI (authenticated), Docker, jq."
      exit 0
      ;;
    *) echo "Unknown argument: $arg"; exit 1 ;;
  esac
done

# ── Preflight checks ────────────────────────────────────────────────
echo "=== Magic Bracket Worker Setup ==="
echo ""

# Check jq
if ! command -v jq &>/dev/null; then
  echo "ERROR: jq not found. Install it:"
  echo "  macOS:  brew install jq"
  echo "  Linux:  sudo apt install jq"
  exit 1
fi

# Check gcloud
if ! command -v gcloud &>/dev/null; then
  echo "ERROR: gcloud CLI not found. Install it:"
  echo "  macOS:  brew install --cask google-cloud-sdk"
  echo "  Linux:  https://cloud.google.com/sdk/docs/install"
  exit 1
fi

# Check gcloud project
PROJECT_ID=$(gcloud config get-value project 2>/dev/null || true)
if [ -z "$PROJECT_ID" ]; then
  echo "ERROR: No GCP project set. Run: gcloud config set project YOUR_PROJECT_ID"
  exit 1
fi
echo "GCP project: $PROJECT_ID"

# Check gcloud ADC
if ! gcloud auth application-default print-access-token &>/dev/null 2>&1; then
  echo "ERROR: No Application Default Credentials. Run: gcloud auth application-default login"
  exit 1
fi
echo "GCP credentials: OK"

# Check Docker
if ! command -v docker &>/dev/null; then
  echo "ERROR: Docker not found. Install Docker Desktop (macOS) or docker engine (Linux)."
  exit 1
fi

if ! docker info &>/dev/null 2>&1; then
  echo "ERROR: Docker daemon not running. Start Docker Desktop or the docker service."
  exit 1
fi
echo "Docker: OK"

# ── Read worker-host-config from Secret Manager ─────────────────────
echo ""
echo "Reading config from Secret Manager ($SECRET_NAME)..."

HOST_CONFIG=$(gcloud secrets versions access latest --secret="$SECRET_NAME" --project="$PROJECT_ID" 2>&1) || {
  echo "ERROR: Failed to read secret '$SECRET_NAME' from Secret Manager."
  echo "$HOST_CONFIG"
  echo ""
  echo "Make sure you've run the 'Provision Worker' GitHub Actions workflow first."
  echo "  gh workflow run provision-worker.yml"
  exit 1
}

# ── Parse config and write files ─────────────────────────────────────
echo "Writing config files..."

# Extract SA key → worker/sa.json
echo "$HOST_CONFIG" | jq -r '.sa_key' > "$WORKER_DIR/sa.json"
chmod 600 "$WORKER_DIR/sa.json"
echo "  worker/sa.json"

# Extract host-level env vars → worker/.env
IMAGE_NAME=$(echo "$HOST_CONFIG" | jq -r '.IMAGE_NAME')
GHCR_USER=$(echo "$HOST_CONFIG" | jq -r '.GHCR_USER')
GHCR_TOKEN=$(echo "$HOST_CONFIG" | jq -r '.GHCR_TOKEN')

cat > "$WORKER_DIR/.env" <<EOF
# Auto-generated by setup-worker.sh — do not edit manually.
# Re-run ./scripts/setup-worker.sh to update.

# Host-level Docker Compose config (worker runtime config comes from Secret Manager)
SA_KEY_PATH=./sa.json
GOOGLE_CLOUD_PROJECT=$PROJECT_ID
IMAGE_NAME=$IMAGE_NAME
GHCR_USER=$GHCR_USER
GHCR_TOKEN=$GHCR_TOKEN
EOF

if [ -n "$WORKER_ID" ]; then
  echo "WORKER_ID=$WORKER_ID" >> "$WORKER_DIR/.env"
fi

chmod 600 "$WORKER_DIR/.env"
echo "  worker/.env"

# ── Stop existing containers ─────────────────────────────────────────
if docker ps -q --filter "name=magic-bracket-worker" 2>/dev/null | grep -q .; then
  echo ""
  echo "Stopping existing worker containers..."
  cd "$WORKER_DIR"
  docker compose -f docker-compose.yml -f docker-compose.watchtower.yml down 2>/dev/null || true
fi

# ── Docker login to GHCR ─────────────────────────────────────────────
echo ""
echo "Logging into GHCR..."
echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin

# ── Pull and start ────────────────────────────────────────────────────
echo ""
echo "Pulling latest worker image..."
cd "$WORKER_DIR"
docker compose -f docker-compose.yml -f docker-compose.watchtower.yml pull worker

echo ""
echo "Starting worker + Watchtower..."
docker compose -f docker-compose.yml -f docker-compose.watchtower.yml up -d

echo ""
echo "=== Setup complete! ==="
echo ""
echo "Useful commands:"
echo "  docker compose -f worker/docker-compose.yml -f worker/docker-compose.watchtower.yml logs -f worker"
echo "  docker compose -f worker/docker-compose.yml -f worker/docker-compose.watchtower.yml logs -f watchtower"
echo ""
echo "To update secrets: re-run the 'Provision Worker' workflow, then re-run this script."
